package model;
// Generated Sep 13, 2017 1:44:35 PM by Hibernate Tools 3.6.0



/**
 * Appointment generated by hbm2java
 */
public class Appointment  implements java.io.Serializable {


     private String appoId;
     private String docId;
     private String day;
     private String time;

    public Appointment() {
    }

	
    public Appointment(String appoId) {
        this.appoId = appoId;
    }
    public Appointment(String appoId, String docId, String day, String time) {
       this.appoId = appoId;
       this.docId = docId;
       this.day = day;
       this.time = time;
    }
   
    public String getAppoId() {
        return this.appoId;
    }
    
    public void setAppoId(String appoId) {
        this.appoId = appoId;
    }
    public String getDocId() {
        return this.docId;
    }
    
    public void setDocId(String docId) {
        this.docId = docId;
    }
    public String getDay() {
        return this.day;
    }
    
    public void setDay(String day) {
        this.day = day;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }




}


