package model;
// Generated Sep 13, 2017 1:44:35 PM by Hibernate Tools 3.6.0



/**
 * CustomerDaig generated by hbm2java
 */
public class CustomerDaig  implements java.io.Serializable {


     private String mrNo;
     private String customerName;
     private String contactNo;
     private String daigName;

    public CustomerDaig() {
    }

	
    public CustomerDaig(String mrNo) {
        this.mrNo = mrNo;
    }
    public CustomerDaig(String mrNo, String customerName, String contactNo, String daigName) {
       this.mrNo = mrNo;
       this.customerName = customerName;
       this.contactNo = contactNo;
       this.daigName = daigName;
    }
   
    public String getMrNo() {
        return this.mrNo;
    }
    
    public void setMrNo(String mrNo) {
        this.mrNo = mrNo;
    }
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }
    public String getDaigName() {
        return this.daigName;
    }
    
    public void setDaigName(String daigName) {
        this.daigName = daigName;
    }




}


