package model;
// Generated Sep 13, 2017 1:44:35 PM by Hibernate Tools 3.6.0



/**
 * Department generated by hbm2java
 */
public class Department  implements java.io.Serializable {


     private String deptId;
     private String deptName;

    public Department() {
    }

	
    public Department(String deptId) {
        this.deptId = deptId;
    }
    public Department(String deptId, String deptName) {
       this.deptId = deptId;
       this.deptName = deptName;
    }
   
    public String getDeptId() {
        return this.deptId;
    }
    
    public void setDeptId(String deptId) {
        this.deptId = deptId;
    }
    public String getDeptName() {
        return this.deptName;
    }
    
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }




}


